Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\pc\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
con = duckdb.connect(database=':memory:')

parquet_file_path = 'train.parquet/train.parquet'

sample_size = 1000000

con.execute(f"CREATE TABLE train_sample AS SELECT * FROM read_parquet('{parquet_file_path}') USING SAMPLE {sample_size} ROWS")

df_sample = con.execute("SELECT * FROM train_sample LIMIT 5").fetchdf()
print("Initial Rows from the Sample Dataset:")
print(df_sample)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mIOException[0m                               Traceback (most recent call last)
Cell [1;32mIn [2], line 7[0m
[0;32m      3[0m parquet_file_path [38;5;241m=[39m [38;5;124m'[39m[38;5;124mtrain.parquet/train.parquet[39m[38;5;124m'[39m
[0;32m      5[0m sample_size [38;5;241m=[39m [38;5;241m1000000[39m
[1;32m----> 7[0m con[38;5;241m.[39mexecute([38;5;124mf[39m[38;5;124m"[39m[38;5;124mCREATE TABLE train_sample AS SELECT * FROM read_parquet([39m[38;5;124m'[39m[38;5;132;01m{[39;00mparquet_file_path[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m) USING SAMPLE [39m[38;5;132;01m{[39;00msample_size[38;5;132;01m}[39;00m[38;5;124m ROWS[39m[38;5;124m"[39m)
[0;32m      9[0m df_sample [38;5;241m=[39m con[38;5;241m.[39mexecute([38;5;124m"[39m[38;5;124mSELECT * FROM train_sample LIMIT 5[39m[38;5;124m"[39m)[38;5;241m.[39mfetchdf()
[0;32m     10[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mInitial Rows from the Sample Dataset:[39m[38;5;124m"[39m)

[1;31mIOException[0m: IO Error: No files found that match the pattern "train.parquet/train.parquet"

